package com.loujin.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig yi18DaoConfig;
    private final DaoConfig yi18_ZDaoConfig;

    private final Yi18Dao yi18Dao;
    private final Yi18_ZDao yi18_ZDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        yi18DaoConfig = daoConfigMap.get(Yi18Dao.class).clone();
        yi18DaoConfig.initIdentityScope(type);

        yi18_ZDaoConfig = daoConfigMap.get(Yi18_ZDao.class).clone();
        yi18_ZDaoConfig.initIdentityScope(type);

        yi18Dao = new Yi18Dao(yi18DaoConfig, this);
        yi18_ZDao = new Yi18_ZDao(yi18_ZDaoConfig, this);

        registerDao(Yi18.class, yi18Dao);
        registerDao(Yi18_Z.class, yi18_ZDao);
    }
    
    public void clear() {
        yi18DaoConfig.getIdentityScope().clear();
        yi18_ZDaoConfig.getIdentityScope().clear();
    }

    public Yi18Dao getYi18Dao() {
        return yi18Dao;
    }

    public Yi18_ZDao getYi18_ZDao() {
        return yi18_ZDao;
    }

}
