package com.loujin.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table YI18__Z.
 */
public class Yi18_Z {

    private Integer id;
    private String name;
    private String cookclass;

    public Yi18_Z() {
    }

    public Yi18_Z(Integer id, String name, String cookclass) {
        this.id = id;
        this.name = name;
        this.cookclass = cookclass;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCookclass() {
        return cookclass;
    }

    public void setCookclass(String cookclass) {
        this.cookclass = cookclass;
    }

}
